server: 
  port: 1130
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:
    url: jdbc:mysql://192.168.50.128:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    database: MySQL
    show-sql: true
